// This file is @generated by wasmcloud/weld-codegen 0.5.0.
// It is not intended for manual editing.
// namespace: com.oneitfarm.wasm.uppercase

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// Parameters sent for Uppercase
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UppercaseRequest {
    /// method to be Uppercased
    #[serde(default)]
    pub data: String,
}

// Encode UppercaseRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_uppercase_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UppercaseRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(1)?;
    e.str("data")?;
    e.str(&val.data)?;
    Ok(())
}

// Decode UppercaseRequest from cbor input stream
#[doc(hidden)]
pub fn decode_uppercase_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UppercaseRequest, RpcError> {
    let __result = {
        let mut data: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UppercaseRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => data = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "data" => data = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        UppercaseRequest {
            data: if let Some(__x) = data {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UppercaseRequest.data (#0)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// Response to Uppercase
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UppercaseResponse {
    /// response data
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// Indicates a successful authorization
    #[serde(default)]
    pub success: bool,
}

// Encode UppercaseResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_uppercase_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UppercaseResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(2)?;
    if let Some(val) = val.data.as_ref() {
        e.str("data")?;
        e.str(val)?;
    } else {
        e.null()?;
    }
    e.str("success")?;
    e.bool(val.success)?;
    Ok(())
}

// Decode UppercaseResponse from cbor input stream
#[doc(hidden)]
pub fn decode_uppercase_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UppercaseResponse, RpcError> {
    let __result = {
        let mut data: Option<Option<String>> = Some(None);
        let mut success: Option<bool> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UppercaseResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => {
                        data = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    1 => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "data" => {
                        data = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    "success" => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        }
        UppercaseResponse {
            data: data.unwrap(),

            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UppercaseResponse.success (#1)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// Description of Uppercase service
/// wasmbus.actorReceive
#[async_trait]
pub trait Uppercase {
    /// Uppercase - Execute transaction
    async fn upper(&self, ctx: &Context, arg: &UppercaseRequest) -> RpcResult<UppercaseResponse>;
}

/// UppercaseReceiver receives messages defined in the Uppercase service trait
/// Description of Uppercase service
#[doc(hidden)]
#[async_trait]
pub trait UppercaseReceiver: MessageDispatch + Uppercase {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "Upper" => {
                let value: UppercaseRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'UppercaseRequest': {}", e)))?;

                let resp = Uppercase::upper(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Uppercase::{}",
                message.method
            ))),
        }
    }
}

/// UppercaseSender sends messages to a Uppercase service
/// Description of Uppercase service
/// client for sending Uppercase messages
#[derive(Debug)]
pub struct UppercaseSender<T: Transport> {
    transport: T,
}

impl<T: Transport> UppercaseSender<T> {
    /// Constructs a UppercaseSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> UppercaseSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl UppercaseSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Uppercase for UppercaseSender<T> {
    #[allow(unused)]
    /// Uppercase - Execute transaction
    async fn upper(&self, ctx: &Context, arg: &UppercaseRequest) -> RpcResult<UppercaseResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Uppercase.Upper",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: UppercaseResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': UppercaseResponse", e)))?;
        Ok(value)
    }
}
